### ISSUE TITLE
[papis-html] no attribute 'get_lib' related to 'click' package

### ISSUE THREAD

**Issue by ttxtea** [papis/scripts#15]
The following error was produce when using the nice `papis html`.
~~~
INFO:papis-html:Searching in database..
Traceback (most recent call last):
  File "/.local/bin/papis-html", line 8, in <module>
    sys.exit(main())
  File "//.local/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/.local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/.local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/.local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/.local/lib/python3.8/site-packages/papis_html/__init__.py", line 35, in main
    library=papis.api.get_lib(),
AttributeError: module 'papis.api' has no attribute 'get_lib'
~~~

Tried specifying a library with the `-l libname` papis flag, but that was not accepted.

**Comment by alejandrogallo** [comment]
I fixed this issue, now it should work in `papis-html v0.1`

**Comment by ttxtea** [comment]
Thanks a lot. it now perfectly installs via `python3 -m pip install --user papis-html` and generates a html/css library when invocing `papis -l mylib html`. The folder `bibliography` contains the `index.html` and the `library.bib`. They seem to be fine. Yet both in `firefox` and `chromium` when opening `index.html` one could not search or find any of the articles.
